apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crm-bantu-website-tls
  namespace: default
spec:
  secretName: crm-bantu-website-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - oa.bantuqifu.com
    - www.oabantuqifu.com

