apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crmbantu-space-tls
  namespace: default
spec:
  secretName: crmbantu-space-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - www.crmbantu.space

