apiVersion: v1
kind: Service
metadata:
  name: crm-bantu-website-dev
  namespace: default
  labels:
    app: crm-bantu-website-dev
spec:
  type: ClusterIP
  ports:
  - port: 5173
    targetPort: 5173
    protocol: TCP
    name: http
  selector:
    app: crm-bantu-website-dev

